### ISSUE TITLE
Crash before refactoring

### ISSUE THREAD

**Issue by GojaN** [nodirt/git-tf#2]
Hi.

I'm getting an exception for `git tf pull` with the last version. The error seams something simple, here is the console output:

```
$ git tf pull
Checking TFS status. There must be no pending changes...
Fetching from TFS
Last synchronized changeset: 283385
Latest changeset on TFS: 283442
Requesting tf history 283385..283442
Traceback (most recent call last):
  File "/Users/Bruno/bin/git-tf", line 24, in <module>
    GitTfException.run(main)
  File "/Users/Bruno/bin/core.py", line 189, in run
    return body()
  File "/Users/Bruno/bin/git-tf", line 19, in main
    return runpy.run_module(command, run_name='__main__')
  File "/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/runpy.py", line 178, in run_module
    fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "/Users/Bruno/bin/pull.py", line 17, in <module>
    App.run(pull)
  File "/Users/Bruno/bin/core.py", line 152, in run
    return GitTfException.run(_run)
  File "/Users/Bruno/bin/core.py", line 189, in run
    return body()
  File "/Users/Bruno/bin/core.py", line 151, in _run
    body(app)
  File "/Users/Bruno/bin/pull.py", line 6, in pull
    if fetch(app) or git('log master..tfs'):
  File "/Users/Bruno/bin/fetch.py", line 25, in fetch
    history = history[:app.number]
AttributeError: 'NoneType' object has no attribute 'number'
```

**Comment by nodirt** [comment]
Fixed, sorry.
72c53d39080359e22763582237c161b033220fe1
